"""change column names

Revision ID: 120dbba24611
Revises: 89e2dd975e0a
Create Date: 2021-06-21 01:45:47.267915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120dbba24611'
down_revision = '89e2dd975e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('myblogs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('myblogs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
