"""add blog posted time

Revision ID: 52a5c21194c4
Revises: 120dbba24611
Create Date: 2021-06-21 02:17:07.946058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a5c21194c4'
down_revision = '120dbba24611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myblogs', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('myblogs', 'posted')
    # ### end Alembic commands ###
