"""create relationships between tables

Revision ID: 89e2dd975e0a
Revises: ab719d4c5194
Create Date: 2021-06-21 00:22:10.595413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e2dd975e0a'
down_revision = 'ab719d4c5194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'myblogs', ['blog_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.add_column('myblogs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'myblogs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'myblogs', type_='foreignkey')
    op.drop_column('myblogs', 'user_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'blog_id')
    # ### end Alembic commands ###
